apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "calculus-gateway.fullname" . }}
  labels:
    {{- include "calculus-gateway.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.config }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
